---
# handlers file for install-k8s
- name: Restart mysql
  service:
    name: mysql
    state: restarted
    
- name: Restart Kubelet
  service:
    name: kubelet
    state: restarted

- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest